[package]
name = "umbreon-mobile"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.5", features = ["signals"] }
dioxus-mobile = "0.5"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
